=== ssconf/rustyvibes-cherry_blue_pbt-soundpack/mechvibes-extracted/sound-pack-schema/v1/config.schema.json
{
	"$id": "https://mechvibes.com/v1/config.schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Soundpack Config",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"description": "A unique identifier for the pack. Usually assigned by the server."
		},
		"name": {
			"type": "string",
			"description": "The name of the soundpack.",
			"required": true
		},
		"default": {
			"type": "boolean",
			"description": "If this pack is installed by default with a fresh install of mechvibes. Readonly property set by the server.",
			"readOnly": true
		},
		"key_define_type": {
			"type": "string",
			"description": "The type of key defines used in this soundpack.",
			"enum": [
				"single",
				"multi"
			],
			"required": true
		},
		"includes_numpad": {
			"$comment": "Note that, this property is deprecated and will be removed in future versions, BUT it is REQUIRED for functionality.",
			"type": "boolean",
			"description": "If this soundpack includes numpad sounds.",
			"deprecated": true,
			"default": true,
			"required": true
		},
		"sound": {
			"$comment": "This property is only used when key_define_type is 'single', however it's required for 'multi' as well.",
			"type": "string",
			"description": "The sound file to play when a key is pressed.",
			"examples": [
				"sound.ogg",
				"my_sound.mp3"
			],
			"deprecated": true,
			"required": true
		},
		"defines": {
			"type": "object",
			"description": "The key definitions for this soundpack.",
			"properties": {
				"$index": {
					"type": "string",
					"description": "The keycode to define. Use iohook's keycodes.",
					"required": true
				},
				"$if(key_define_type == 'multi')": {
					"$value":{
						"type": "string",
						"description": "The sound file to play when this key is pressed."
					}
				},
				"$if(key_define_type == 'single')": {
					"$value":{
						"type": "array",
						"description": "The sound clip to play when a key is pressed.",
						"valueNames": [
							"start",
							"end"
						]
					}
				}
			},
			"required": true
		},
		"tags": {
			"type": "array",
			"description": "Tags to help users find this soundpack.",
			"items": {
				"type": "string"
			}
		},
		"$comment": "There may be additional properties which are set by the server, which are for information only and not used by the app."
	}
}

=== ssconf/rustyvibes-cherry_blue_pbt-soundpack/cherry-blue-pbt-rustyvibes/config.json
{
  "id": "custom-sound-pack-1582707445334",
  "name": "CherryMX Blue - PBT keycaps",
  "key_define_type": "multi",
  "includes_numpad": false,
  "defines": {
    "1": "key_1.wav",
    "2": "key_2.wav",
    "3": "key_3.wav",
    "4": "key_4.wav",
    "5": "key_5.wav",
    "6": "key_6.wav",
    "7": "key_7.wav",
    "8": "key_8.wav",
    "9": "key_9.wav",
    "10": "key_10.wav",
    "11": "key_11.wav",
    "12": "key_12.wav",
    "13": "key_13.wav",
    "14": "key_14.wav",
    "15": "key_15.wav",
    "16": "key_16.wav",
    "17": "key_17.wav",
    "18": "key_18.wav",
    "19": "key_19.wav",
    "20": "key_20.wav",
    "21": "key_21.wav",
    "22": "key_22.wav",
    "23": "key_23.wav",
    "24": "key_24.wav",
    "25": "key_25.wav",
    "26": "key_26.wav",
    "27": "key_27.wav",
    "28": "key_28.wav",
    "29": "key_29.wav",
    "30": "key_30.wav",
    "31": "key_31.wav",
    "32": "key_32.wav",
    "33": "key_33.wav",
    "34": "key_34.wav",
    "35": "key_35.wav",
    "36": "key_36.wav",
    "37": "key_37.wav",
    "38": "key_38.wav",
    "39": "key_39.wav",
    "40": "key_40.wav",
    "41": "key_41.wav",
    "42": "key_42.wav",
    "43": "key_43.wav",
    "44": "key_44.wav",
    "45": "key_45.wav",
    "46": "key_46.wav",
    "47": "key_47.wav",
    "48": "key_48.wav",
    "49": "key_49.wav",
    "50": "key_50.wav",
    "51": "key_51.wav",
    "52": "key_52.wav",
    "53": "key_53.wav",
    "54": "key_54.wav",
    "55": "key_55.wav",
    "56": "key_56.wav",
    "57": "key_57.wav",
    "58": "key_58.wav",
    "59": "key_59.wav",
    "60": "key_60.wav",
    "61": "key_61.wav",
    "62": "key_62.wav",
    "63": "key_63.wav",
    "64": "key_64.wav",
    "65": "key_65.wav",
    "66": "key_66.wav",
    "67": "key_67.wav",
    "68": "key_68.wav",
    "69": "key_69.wav",
    "70": "key_70.wav",
    "71": "key_71.wav",
    "72": "key_72.wav",
    "73": "key_73.wav",
    "74": "key_74.wav",
    "75": "key_75.wav",
    "76": "key_76.wav",
    "77": "key_77.wav",
    "78": "key_78.wav",
    "79": "key_79.wav",
    "80": "key_80.wav",
    "81": "key_81.wav",
    "82": "key_82.wav",
    "83": "key_83.wav",
    "87": "key_87.wav",
    "88": "key_88.wav",
    "3612": "key_3612.wav",
    "3613": "key_3613.wav",
    "3637": "key_3637.wav",
    "3639": "key_3639.wav",
    "3640": "key_3640.wav",
    "3653": "key_3653.wav",
    "3655": "key_3655.wav",
    "3657": "key_3657.wav",
    "3663": "key_3663.wav",
    "3665": "key_3665.wav",
    "3666": "key_3666.wav",
    "3667": "key_3667.wav",
    "3675": "key_3675.wav",
    "3676": "key_3676.wav",
    "3677": "key_3677.wav",
    "57416": "key_57416.wav",
    "57419": "key_57419.wav",
    "57421": "key_57421.wav",
    "57424": "key_57424.wav",
    "60999": "key_60999.wav",
    "61000": "key_61000.wav",
    "61001": "key_61001.wav",
    "61003": "key_61003.wav",
    "61005": "key_61005.wav",
    "61007": "key_61007.wav",
    "61008": "key_61008.wav",
    "61009": "key_61009.wav",
    "61010": "key_61010.wav",
    "61011": "key_61011.wav"
  }
}
